// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	Void
	Message
	Session
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Session struct {
	Id     int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Session) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Session) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Void)(nil), "grpc.Void")
	proto.RegisterType((*Message)(nil), "grpc.Message")
	proto.RegisterType((*Session)(nil), "grpc.Session")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Ironman service

type IronmanClient interface {
	// RPC Calls for Ironman
	Ping(ctx context.Context, in *Message, opts ...grpc1.CallOption) (*Message, error)
}

type ironmanClient struct {
	cc *grpc1.ClientConn
}

func NewIronmanClient(cc *grpc1.ClientConn) IronmanClient {
	return &ironmanClient{cc}
}

func (c *ironmanClient) Ping(ctx context.Context, in *Message, opts ...grpc1.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc1.Invoke(ctx, "/grpc.Ironman/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ironman service

type IronmanServer interface {
	// RPC Calls for Ironman
	Ping(context.Context, *Message) (*Message, error)
}

func RegisterIronmanServer(s *grpc1.Server, srv IronmanServer) {
	s.RegisterService(&_Ironman_serviceDesc, srv)
}

func _Ironman_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IronmanServer).Ping(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Ironman/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IronmanServer).Ping(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ironman_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Ironman",
	HandlerType: (*IronmanServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Ironman_Ping_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

// Client API for Batman service

type BatmanClient interface {
	IronManCallback(ctx context.Context, in *Session, opts ...grpc1.CallOption) (*Void, error)
}

type batmanClient struct {
	cc *grpc1.ClientConn
}

func NewBatmanClient(cc *grpc1.ClientConn) BatmanClient {
	return &batmanClient{cc}
}

func (c *batmanClient) IronManCallback(ctx context.Context, in *Session, opts ...grpc1.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc1.Invoke(ctx, "/grpc.Batman/IronManCallback", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Batman service

type BatmanServer interface {
	IronManCallback(context.Context, *Session) (*Void, error)
}

func RegisterBatmanServer(s *grpc1.Server, srv BatmanServer) {
	s.RegisterService(&_Batman_serviceDesc, srv)
}

func _Batman_IronManCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatmanServer).IronManCallback(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Batman/IronManCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatmanServer).IronManCallback(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

var _Batman_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Batman",
	HandlerType: (*BatmanServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "IronManCallback",
			Handler:    _Batman_IronManCallback_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x6d, 0x89, 0x29, 0xfb, 0x40, 0x85, 0x20, 0xb2, 0x2c, 0x08, 0x12, 0x41, 0x3c, 0x48,
	0x61, 0x57, 0xf0, 0x07, 0xd4, 0x83, 0x78, 0x58, 0x28, 0x15, 0xbc, 0xbf, 0x26, 0x21, 0x04, 0xdb,
	0x97, 0x92, 0x44, 0xf0, 0xe7, 0x4b, 0x62, 0x3d, 0xec, 0x6d, 0x86, 0xe1, 0x63, 0x66, 0x00, 0x6c,
	0x58, 0x54, 0xbb, 0x04, 0x9f, 0xbc, 0x60, 0x59, 0x4b, 0x0e, 0xec, 0xd3, 0x3b, 0x2d, 0x6f, 0xa1,
	0x39, 0x9a, 0x18, 0xd1, 0x1a, 0x21, 0x80, 0x25, 0xf3, 0x93, 0xb6, 0xd5, 0x5d, 0xf5, 0xb8, 0x19,
	0x8a, 0x96, 0x7b, 0x68, 0x3e, 0x4c, 0x8c, 0xce, 0x93, 0xb8, 0x84, 0xda, 0xe9, 0x12, 0x9e, 0x0f,
	0xb5, 0xd3, 0xe2, 0x06, 0x78, 0x4c, 0x98, 0xbe, 0xe3, 0xb6, 0x2e, 0xc0, 0xea, 0x0e, 0x7b, 0x68,
	0xde, 0x83, 0xa7, 0x19, 0x49, 0x3c, 0x00, 0xeb, 0x1d, 0x59, 0x71, 0xd1, 0x96, 0xfe, 0xb5, 0x68,
	0x77, 0x6a, 0xe5, 0xd9, 0xe1, 0x05, 0x78, 0x87, 0x29, 0x13, 0x4f, 0x70, 0x95, 0xe1, 0x23, 0xd2,
	0x2b, 0x4e, 0xd3, 0x88, 0xea, 0xeb, 0x1f, 0x5e, 0x67, 0xec, 0xe0, 0xcf, 0xe6, 0xf1, 0xdd, 0x3d,
	0x5c, 0x2b, 0x3f, 0xb7, 0x33, 0x92, 0xb3, 0x48, 0x1a, 0x49, 0x97, 0xb0, 0xdb, 0xbc, 0x85, 0x45,
	0xf5, 0xf9, 0x6d, 0x5f, 0x8d, 0xbc, 0xdc, 0x7e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x51,
	0x3c, 0x63, 0x04, 0x01, 0x00, 0x00,
}
