# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hall_pb2 as hall__pb2


class IronmanStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/hall.Ironman/Ping',
        request_serializer=hall__pb2.Message.SerializeToString,
        response_deserializer=hall__pb2.Message.FromString,
        )


class IronmanServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    """RPC Calls for Ironman
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IronmanServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=hall__pb2.Message.FromString,
          response_serializer=hall__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hall.Ironman', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BatmanStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IronmanCallback = channel.unary_unary(
        '/hall.Batman/IronmanCallback',
        request_serializer=hall__pb2.Session.SerializeToString,
        response_deserializer=hall__pb2.Void.FromString,
        )


class BatmanServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def IronmanCallback(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BatmanServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IronmanCallback': grpc.unary_unary_rpc_method_handler(
          servicer.IronmanCallback,
          request_deserializer=hall__pb2.Session.FromString,
          response_serializer=hall__pb2.Void.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hall.Batman', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
