# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hall.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hall.proto',
  package='hall',
  syntax='proto3',
  serialized_pb=_b('\n\nhall.proto\x12\x04hall\"\x06\n\x04Void\"\x17\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t20\n\x06Ironman\x12&\n\x04Ping\x12\r.hall.Message\x1a\r.hall.Message\"\x00\x32\x35\n\x06\x42\x61tman\x12+\n\x0eIronmanCallback\x12\r.hall.Session\x1a\n.hall.VoidB\x1e\n\x0f\x63om.aircto.hallB\tHallProtoP\x01\x62\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='hall.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=26,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='hall.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='hall.Message.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=51,
)


_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='hall.Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hall.Session.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='hall.Session.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Session'] = _SESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'hall_pb2'
  # @@protoc_insertion_point(class_scope:hall.Void)
  ))
_sym_db.RegisterMessage(Void)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'hall_pb2'
  # @@protoc_insertion_point(class_scope:hall.Message)
  ))
_sym_db.RegisterMessage(Message)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), dict(
  DESCRIPTOR = _SESSION,
  __module__ = 'hall_pb2'
  # @@protoc_insertion_point(class_scope:hall.Session)
  ))
_sym_db.RegisterMessage(Session)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017com.aircto.hallB\tHallProtoP\001'))

_IRONMAN = _descriptor.ServiceDescriptor(
  name='Ironman',
  full_name='hall.Ironman',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=92,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='hall.Ironman.Ping',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IRONMAN)

DESCRIPTOR.services_by_name['Ironman'] = _IRONMAN


_BATMAN = _descriptor.ServiceDescriptor(
  name='Batman',
  full_name='hall.Batman',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=142,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='IronmanCallback',
    full_name='hall.Batman.IronmanCallback',
    index=0,
    containing_service=None,
    input_type=_SESSION,
    output_type=_VOID,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BATMAN)

DESCRIPTOR.services_by_name['Batman'] = _BATMAN

# @@protoc_insertion_point(module_scope)
